/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { LendingSDKError } from "./lendingsdkerror.js";

export type ApiErrorInvalidInputData = {
  status: number;
  error: string;
};

export class ApiErrorInvalidInput extends LendingSDKError {
  status: number;
  error: string;

  /** The original data that was passed to this error instance. */
  data$: ApiErrorInvalidInputData;

  constructor(
    err: ApiErrorInvalidInputData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.status = err.status;
    this.error = err.error;

    this.name = "ApiErrorInvalidInput";
  }
}

/** @internal */
export const ApiErrorInvalidInput$inboundSchema: z.ZodType<
  ApiErrorInvalidInput,
  z.ZodTypeDef,
  unknown
> = z.object({
  status: z.number().int(),
  error: z.string(),
  request$: z.instanceof(Request),
  response$: z.instanceof(Response),
  body$: z.string(),
})
  .transform((v) => {
    return new ApiErrorInvalidInput(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  });
