/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { AccountingSDKError } from "./accountingsdkerror.js";

/**
 * Not Found error
 */
export type ApiErrorNotFoundData = {
  status: number;
  error: string;
  code: string;
};

/**
 * Not Found error
 */
export class ApiErrorNotFound extends AccountingSDKError {
  status: number;
  error: string;
  code: string;

  /** The original data that was passed to this error instance. */
  data$: ApiErrorNotFoundData;

  constructor(
    err: ApiErrorNotFoundData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.status = err.status;
    this.error = err.error;
    this.code = err.code;

    this.name = "ApiErrorNotFound";
  }
}

/** @internal */
export const ApiErrorNotFound$inboundSchema: z.ZodType<
  ApiErrorNotFound,
  z.ZodTypeDef,
  unknown
> = z.object({
  status: z.number().int(),
  error: z.string(),
  code: z.string(),
  request$: z.instanceof(Request),
  response$: z.instanceof(Response),
  body$: z.string(),
})
  .transform((v) => {
    return new ApiErrorNotFound(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  });
