/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { AccountingSDKError } from "./accountingsdkerror.js";

/**
 * Unauthorized error
 */
export type ApiErrorUnauthorizedData = {
  status: number;
  error: string;
};

/**
 * Unauthorized error
 */
export class ApiErrorUnauthorized extends AccountingSDKError {
  status: number;
  error: string;

  /** The original data that was passed to this error instance. */
  data$: ApiErrorUnauthorizedData;

  constructor(
    err: ApiErrorUnauthorizedData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.status = err.status;
    this.error = err.error;

    this.name = "ApiErrorUnauthorized";
  }
}

/** @internal */
export const ApiErrorUnauthorized$inboundSchema: z.ZodType<
  ApiErrorUnauthorized,
  z.ZodTypeDef,
  unknown
> = z.object({
  status: z.number().int(),
  error: z.string(),
  request$: z.instanceof(Request),
  response$: z.instanceof(Response),
  body$: z.string(),
})
  .transform((v) => {
    return new ApiErrorUnauthorized(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  });
