/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

export type DeleteOrderRequest = {
  /**
   * ID of the order that needs to be deleted
   */
  orderId: number;
};

/** @internal */
export type DeleteOrderRequest$Outbound = {
  orderId: number;
};

/** @internal */
export const DeleteOrderRequest$outboundSchema: z.ZodType<
  DeleteOrderRequest$Outbound,
  z.ZodTypeDef,
  DeleteOrderRequest
> = z.object({
  orderId: z.number().int(),
});

export function deleteOrderRequestToJSON(
  deleteOrderRequest: DeleteOrderRequest,
): string {
  return JSON.stringify(
    DeleteOrderRequest$outboundSchema.parse(deleteOrderRequest),
  );
}
