/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";

export type DeletePetRequest = {
  apiKey?: string | undefined;
  /**
   * Pet id to delete
   */
  petId: number;
};

/** @internal */
export type DeletePetRequest$Outbound = {
  api_key?: string | undefined;
  petId: number;
};

/** @internal */
export const DeletePetRequest$outboundSchema: z.ZodType<
  DeletePetRequest$Outbound,
  z.ZodTypeDef,
  DeletePetRequest
> = z.object({
  apiKey: z.string().optional(),
  petId: z.number().int(),
}).transform((v) => {
  return remap$(v, {
    apiKey: "api_key",
  });
});

export function deletePetRequestToJSON(
  deletePetRequest: DeletePetRequest,
): string {
  return JSON.stringify(
    DeletePetRequest$outboundSchema.parse(deletePetRequest),
  );
}
