/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

export type DeleteUserRequest = {
  /**
   * The name that needs to be deleted
   */
  username: string;
};

/** @internal */
export type DeleteUserRequest$Outbound = {
  username: string;
};

/** @internal */
export const DeleteUserRequest$outboundSchema: z.ZodType<
  DeleteUserRequest$Outbound,
  z.ZodTypeDef,
  DeleteUserRequest
> = z.object({
  username: z.string(),
});

export function deleteUserRequestToJSON(
  deleteUserRequest: DeleteUserRequest,
): string {
  return JSON.stringify(
    DeleteUserRequest$outboundSchema.parse(deleteUserRequest),
  );
}
