/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

export type FindPetsByTagsRequest = {
  /**
   * Tags to filter by
   */
  tags?: Array<string> | undefined;
};

/** @internal */
export type FindPetsByTagsRequest$Outbound = {
  tags?: Array<string> | undefined;
};

/** @internal */
export const FindPetsByTagsRequest$outboundSchema: z.ZodType<
  FindPetsByTagsRequest$Outbound,
  z.ZodTypeDef,
  FindPetsByTagsRequest
> = z.object({
  tags: z.array(z.string()).optional(),
});

export function findPetsByTagsRequestToJSON(
  findPetsByTagsRequest: FindPetsByTagsRequest,
): string {
  return JSON.stringify(
    FindPetsByTagsRequest$outboundSchema.parse(findPetsByTagsRequest),
  );
}
