/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { ClosedEnum } from "../../types/enums.js";

/**
 * Status values that need to be considered for filter
 */
export const Status = {
  Available: "available",
  Pending: "pending",
  Sold: "sold",
} as const;
/**
 * Status values that need to be considered for filter
 */
export type Status = ClosedEnum<typeof Status>;

export type FindPetsByStatusTypesRequest = {
  /**
   * Status values that need to be considered for filter
   */
  status?: Status | undefined;
};

/** @internal */
export const Status$outboundSchema: z.ZodNativeEnum<typeof Status> = z
  .nativeEnum(Status);

/** @internal */
export type FindPetsByStatusTypesRequest$Outbound = {
  status: string;
};

/** @internal */
export const FindPetsByStatusTypesRequest$outboundSchema: z.ZodType<
  FindPetsByStatusTypesRequest$Outbound,
  z.ZodTypeDef,
  FindPetsByStatusTypesRequest
> = z.object({
  status: Status$outboundSchema.default("available"),
});

export function findPetsByStatusTypesRequestToJSON(
  findPetsByStatusTypesRequest: FindPetsByStatusTypesRequest,
): string {
  return JSON.stringify(
    FindPetsByStatusTypesRequest$outboundSchema.parse(
      findPetsByStatusTypesRequest,
    ),
  );
}
