/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

export type GetPetByIDSRequest = {
  /**
   * ID of pet to return
   */
  petId: number;
};

/** @internal */
export type GetPetByIDSRequest$Outbound = {
  petId: number;
};

/** @internal */
export const GetPetByIDSRequest$outboundSchema: z.ZodType<
  GetPetByIDSRequest$Outbound,
  z.ZodTypeDef,
  GetPetByIDSRequest
> = z.object({
  petId: z.number().int(),
});

export function getPetByIDSRequestToJSON(
  getPetByIDSRequest: GetPetByIDSRequest,
): string {
  return JSON.stringify(
    GetPetByIDSRequest$outboundSchema.parse(getPetByIDSRequest),
  );
}
