/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

export type GetUserByNameRequest = {
  /**
   * The name that needs to be fetched. Use user1 for testing.
   */
  username: string;
};

/** @internal */
export type GetUserByNameRequest$Outbound = {
  username: string;
};

/** @internal */
export const GetUserByNameRequest$outboundSchema: z.ZodType<
  GetUserByNameRequest$Outbound,
  z.ZodTypeDef,
  GetUserByNameRequest
> = z.object({
  username: z.string(),
});

export function getUserByNameRequestToJSON(
  getUserByNameRequest: GetUserByNameRequest,
): string {
  return JSON.stringify(
    GetUserByNameRequest$outboundSchema.parse(getUserByNameRequest),
  );
}
