/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type LoginUserRequest = {
  /**
   * The user name for login
   */
  username?: string | undefined;
  /**
   * The password for login in clear text
   */
  password?: string | undefined;
};

export type LoginUserResponse = {
  headers: { [k: string]: Array<string> };
  result: string;
};

/** @internal */
export type LoginUserRequest$Outbound = {
  username?: string | undefined;
  password?: string | undefined;
};

/** @internal */
export const LoginUserRequest$outboundSchema: z.ZodType<
  LoginUserRequest$Outbound,
  z.ZodTypeDef,
  LoginUserRequest
> = z.object({
  username: z.string().optional(),
  password: z.string().optional(),
});

export function loginUserRequestToJSON(
  loginUserRequest: LoginUserRequest,
): string {
  return JSON.stringify(
    LoginUserRequest$outboundSchema.parse(loginUserRequest),
  );
}

/** @internal */
export const LoginUserResponse$inboundSchema: z.ZodType<
  LoginUserResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  Headers: z.record(z.array(z.string())).default({}),
  Result: z.string(),
}).transform((v) => {
  return remap$(v, {
    "Headers": "headers",
    "Result": "result",
  });
});

export function loginUserResponseFromJSON(
  jsonString: string,
): SafeParseResult<LoginUserResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => LoginUserResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'LoginUserResponse' from JSON`,
  );
}
