/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { expect, test } from "vitest";
import { LendingSDK } from "../index.js";
import { createTestHTTPClient } from "./testclient.js";

test("Pets List Pets", async () => {
  const lendingSDK = new LendingSDK({
    serverURL: process.env["TEST_SERVER_URL"] ?? "http://localhost:18080",
    httpClient: createTestHTTPClient("listPets"),
  });

  const result = await lendingSDK.pets.listPets({});
  expect(result).toBeDefined();
  expect(result.result).toBeDefined();
  expect(result.result).toEqual([
    {
      id: 767425,
      name: "<value>",
    },
  ]);
});

test("Pets Create Pets", async () => {
  const lendingSDK = new LendingSDK({
    serverURL: process.env["TEST_SERVER_URL"] ?? "http://localhost:18080",
    httpClient: createTestHTTPClient("createPets"),
  });

  const result = await lendingSDK.pets.createPets({
    id: 596804,
    name: "<value>",
  });
  expect(result).toBeDefined();
  expect(result).toEqual({
    code: 589113,
    message: "<value>",
  });
});

test("Pets Show Pet By Id", async () => {
  const lendingSDK = new LendingSDK({
    serverURL: process.env["TEST_SERVER_URL"] ?? "http://localhost:18080",
    httpClient: createTestHTTPClient("showPetById"),
  });

  const result = await lendingSDK.pets.showPetById({
    petId: "<id>",
  });
  expect(result).toBeDefined();
  expect(result).toEqual({
    id: 763078,
    name: "<value>",
  });
});
