/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { assert, it } from "vitest";

it.skip("Pets List Pets", async () => {
  assert.fail(
    "incomplete test found please make sure to address the following errors: [`workflow step listPets.test referencing operation listPets not found in document`]",
  );
});

it.skip("Pets Create Pets", async () => {
  assert.fail(
    "incomplete test found please make sure to address the following errors: [`workflow step createPets.test referencing operation createPets not found in document`]",
  );
});

it.skip("Pets Show Pet By Id", async () => {
  assert.fail(
    "incomplete test found please make sure to address the following errors: [`workflow step showPetById.test referencing operation showPetById not found in document`]",
  );
});
