/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { expect, test } from "vitest";
import { LendingSDK } from "../index.js";
import { createTestHTTPClient } from "./testclient.js";

test("Store Get Inventory", async () => {
  const testHttpClient = createTestHTTPClient("getInventory");

  const lendingSDK = new LendingSDK({
    serverURL: process.env["TEST_SERVER_URL"] ?? "http://localhost:18080",
    httpClient: testHttpClient,
    apiKey: "<YOUR_API_KEY_HERE>",
  });

  const result = await lendingSDK.store.getInventory();
  expect(result).toBeDefined();
  expect(result).toEqual({
    "key": 111959,
    "key1": 333452,
    "key2": 973245,
  });
});

test("Store Place Order", async () => {
  const testHttpClient = createTestHTTPClient("placeOrder");

  const lendingSDK = new LendingSDK({
    serverURL: process.env["TEST_SERVER_URL"] ?? "http://localhost:18080",
    httpClient: testHttpClient,
    apiKey: "<YOUR_API_KEY_HERE>",
  });

  const result = await lendingSDK.store.placeOrder({
    id: 10,
    petId: 198772,
    quantity: 7,
    status: "approved",
  });
  expect(result).toBeDefined();
  expect(result).toEqual({
    id: 10,
    petId: 198772,
    quantity: 7,
    status: "approved",
  });
});

test("Store Get Order By Id", async () => {
  const testHttpClient = createTestHTTPClient("getOrderById");

  const lendingSDK = new LendingSDK({
    serverURL: process.env["TEST_SERVER_URL"] ?? "http://localhost:18080",
    httpClient: testHttpClient,
    apiKey: "<YOUR_API_KEY_HERE>",
  });

  const result = await lendingSDK.store.getOrderById({
    orderId: 728529,
  });
  expect(result).toBeDefined();
  expect(result).toEqual({
    id: 10,
    petId: 198772,
    quantity: 7,
    status: "approved",
  });
});

test("Store Delete Order", async () => {
  const testHttpClient = createTestHTTPClient("deleteOrder");

  const lendingSDK = new LendingSDK({
    serverURL: process.env["TEST_SERVER_URL"] ?? "http://localhost:18080",
    httpClient: testHttpClient,
    apiKey: "<YOUR_API_KEY_HERE>",
  });

  const result = await lendingSDK.store.deleteOrder({
    orderId: 690575,
  });
  expect(result).toBeDefined();
  expect(result).toEqual({
    id: 10,
    petId: 198772,
    quantity: 7,
    status: "approved",
  });
});
