/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type ApiResponse = {
  code?: number | undefined;
  type?: string | undefined;
  message?: string | undefined;
};

/** @internal */
export const ApiResponse$inboundSchema: z.ZodType<
  ApiResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  code: z.number().int().optional(),
  type: z.string().optional(),
  message: z.string().optional(),
});

export function apiResponseFromJSON(
  jsonString: string,
): SafeParseResult<ApiResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ApiResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ApiResponse' from JSON`,
  );
}
