/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { expect, test } from "vitest";
import { AccountingSDK } from "../index.js";
import { createTestHTTPClient } from "./testclient.js";

test("Pets List Pets", async () => {
  const accountingSDK = new AccountingSDK({
    serverURL: process.env["TEST_SERVER_URL"] ?? "http://localhost:18080",
    httpClient: createTestHTTPClient("listPets"),
  });

  const result = await accountingSDK.pets.listPets({});
  expect(result).toBeDefined();
});

test("Pets Create Pets", async () => {
  const accountingSDK = new AccountingSDK({
    serverURL: process.env["TEST_SERVER_URL"] ?? "http://localhost:18080",
    httpClient: createTestHTTPClient("createPets"),
  });

  const result = await accountingSDK.pets.createPets({
    id: 596804,
    name: "<value>",
  });
});

test("Pets Show Pet By Id", async () => {
  const accountingSDK = new AccountingSDK({
    serverURL: process.env["TEST_SERVER_URL"] ?? "http://localhost:18080",
    httpClient: createTestHTTPClient("showPetById"),
  });

  const result = await accountingSDK.pets.showPetById({
    petId: "<id>",
  });
  expect(result).toBeDefined();
});
