workflowVersion: 1.0.0
speakeasyVersion: 1.357.1
sources:
    source1:
        inputs:
            - location: https://raw.githubusercontent.com/OAI/OpenAPI-Specification/main/examples/v3.0/petstore.yaml
        registry:
            location: registry.speakeasyapi.dev/ryan-local/ryan-telemetry/source-1
targets:
    accounting:
        target: typescript
        source: source1
        output: ./accounting
        publish:
            npm:
                token: $npm_token
    finance:
        target: typescript
        source: source1
        output: ./finance
    lending:
        target: typescript
        source: source1
        output: lending
        publish:
            npm:
                token: $npm_token
