workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    source1:
        inputs:
            - location: openapi.yaml
        registry:
            location: registry.speakeasyapi.dev/ryan-local/ryan-telemetry/source-1
targets:
    accounting:
        target: typescript
        source: source1
        output: ./accounting
        publish:
            npm:
                token: $npm_token
        codeSamples:
            registry:
                location: registry.speakeasyapi.dev/ryan-local/ryan-telemetry/source-1-typescript-code-samples
            blocking: false
        testing:
            enabled: true
    finance:
        target: typescript
        source: source1
        output: ./finance
        codeSamples:
            registry:
                location: registry.speakeasyapi.dev/ryan-local/ryan-telemetry/source-1-typescript-code-samples
            blocking: false
        testing:
            enabled: true
    lending:
        target: typescript
        source: source1
        output: lending
        publish:
            npm:
                token: $npm_token
        codeSamples:
            registry:
                location: registry.speakeasyapi.dev/ryan-local/ryan-telemetry/source-1-typescript-code-samples
            blocking: false
        testing:
            enabled: true
