name: Publish ACCOUNTING
permissions:
  checks: write
  contents: write
  pull-requests: write
  statuses: write
on:
  # push:
  #   branches:
  #     - main
  #   paths:
  #     - accounting/.speakeasy/gen.lock
  #     - accounting/RELEASES.md
  workflow_dispatch:
jobs:
  publish:
    uses: speakeasy-api/sdk-generation-action/.github/workflows/sdk-publish.yaml@v15.31.0
    with:
      target: accounting
    secrets:
      github_access_token: ${{ secrets.GITHUB_TOKEN }}
      npm_token: ${{ secrets.NPM_TOKEN_2 }}
      speakeasy_api_key: ${{ secrets.SPEAKEASY_API_KEY }}
